#!/bin/bash
VERSION=$(git describe --tags 2>/dev/null || echo unknown)

BINDIR="$1"
LIBDIR="$2"
shift 2

for file in "$@"
do
    if [[ "$file" == */pish ]]; then
	src="$file"
	dest="$BINDIR/$(basename $file)"
    else
	src="$file"
	dest="$LIBDIR/$(basename $file)"
    fi
    dir=$(dirname "$dest")
    if [[ ! -d "$dir" ]]; then
	mkdir -p "$dir"
	chmod a+rx "$dir"
    fi
    echo -n "Installing $file to $dest ... "
    awk '/%%README%%/ {
		while ((getline line < "README.md") > 0 && line !~ /^Copyright/)
			printf("# %s\n", line);
		next;
	}
	/%%LICENSE%%/ {
		while ((getline line < "LICENSE") > 0)
			printf("# %s\n", line);
		next;
	}
	{
		sub(/%%VERSION%%/, "'$VERSION'", $0);
		print $0;
	}
	' < "$src" > "$dest"
    chmod a+rx "$dest"
    echo "Done"
done
