#!/bin/bash
#
# Provision In SHell.
#
# Version: %%VERSION%%
#
# %%LICENSE%%
#

# ================================================================================
# 1Password Configuration
#
_1PASS=${_1PASS:-1pass}
_1PASS_OP=${_1PASS_OP:-op}
_1PASS_JQ=${_1PASS_JQ:-jq}

# ================================================================================
# 1Password Requirements
#
# This will only pass if user is logged in.
#

function 1pass_logged_in_PREQ()
{
    requirement can_execute "$_1PASS"
    requirement can_execute "$_1PASS_OP"
    requirement can_execute "$_1PASS_JQ"
}

function 1pass_logged_in_DESC()
{
    echo "logged into 1Password"
}

function 1pass_logged_in_TEST()
{
    "$_1PASS" --login-valid
}

# --------------------------------------------------------------------------------
# This will login user if required
#

function 1pass_login_PREQ()
{
    requirement can_execute "$_1PASS"
    requirement can_execute "$_1PASS_OP"
    requirement can_execute "$_1PASS_JQ"
}

function 1pass_login_DESC()
{
    echo "login into 1Password"
}

function 1pass_login_TEST()
{
    "$_1PASS" --login-valid
}

function 1pass_login_LOCAL()
{
    export _1PASS_INPUT=terminal
    $(eval "$_1PASS" --login)
}

# --------------------------------------------------------------------------------

function 1pass_get_user_PREQ()
{
    requirement 1pass_logged_in
}

function 1pass_get_user_DESC()
{
    local user="$1"
    local id="$2"
    echo "has user for \"$user\" in $id"
}

function 1pass_get_user_TEST()
{
    local user="$1"
    local id="$2"
    local USER="$(eval echo \$$id)"
    
    [[ "$USER" != "" ]]
}

function 1pass_get_user_LOCAL()
{
    local user="$1"
    local id="$2"

    eval $id=\""$("$_1PASS" -u "$user")"\"
}

# --------------------------------------------------------------------------------

function 1pass_get_password_PREQ()
{
    requirement 1pass_logged_in
}

function 1pass_get_password_DESC()
{
    local user="$1"
    local id="$2"
    echo "has password for \"$user\" in $id"
}

function 1pass_get_password_TEST()
{
    local user="$1"
    local id="$2"
    local PASSWORD="$(eval echo \$$id)"
    
    [[ "$PASSWORD" != "" ]]
}

function 1pass_get_password_LOCAL()
{
    local user="$1"
    local id="$2"

    eval $id=\""$("$_1PASS" -p "$user")"\"
}

# --------------------------------------------------------------------------------

function 1pass_get_master_password_PREQ()
{
    requirement 1pass_logged_in
}

function 1pass_get_master_password_DESC()
{
    echo "has master password in _1PASS_MASTER_PASSWORD"
}

function 1pass_get_master_password_TEST()
{
    [[ "$_1PASS_MASTER_PASSWORD" != "" ]]
}

function 1pass_get_master_password_LOCAL()
{
    _1PASS_MASTER_PASSWORD="$("$_1PASS" --master-password)"
}
