#!/bin/bash
#
# Apt utilities
#

APT_UPDATED=false

# ================================================================================
# Ensure Apt is up-to-date

function apt_updated_DESC()
{
    echo "apt is updated"
}
    
function apt_updated_TEST()
{
    $APT_UPDATED
}

function apt_updated_SHELL()
{
    sudo apt update
    APT_UPDATED=true
}

# ================================================================================
# Install via apt

function apt_install_DESC()
{
    echo "apt install $1"
}
    
function apt_install_TEST()
{
    [[ $(dpkg-query --show $1 2>/dev/null) != "" ]]
}

function apt_install_SHELL()
{
    sudo apt install -y $1
}

# ================================================================================
# Add repository

function apt_add_repository_DESC()
{
    echo "apt add repository $1"
}
    
function apt_add_repository_TEST()
{
    local id="$1"
    local part="${id##ppa:}"
    local user="${part%%/*}"
    local name="${part##*/}"

    local existing=$(sed -n -e "\%deb http://ppa\..*/$user/$name/.*%p" /etc/apt/sources.list /etc/apt/sources.list.d/*)
    [[ "$existing" != "" ]]
}

function apt_add_repository_SHELL()
{
    local id="$1"
    sudo add-apt-repository -y "$id"
    sudo apt update
}
