#!/bin/bash
#
# Basic requirements
#

# ================================================================================
# Basic requirements
#
function file_exists_DESC()
{
    echo "file \"$1\" exists"
}

function file_exists_TEST()
{
    [[ -f "$1" ]]
}

function directory_exists_DESC()
{
    echo "directory \"$1\" exists"
}

function directory_exists_TEST()
{
    [[ -d "$1" ]]
}

function can_execute_DESC()
{
    echo "can execute \"$1\""
}

function can_execute_TEST()
{
   type -p "$1" >/dev/null
}

# --------------------------------------------------------------------------------
function make_directory_DESC()
{
    echo "directory \"$1\" is created"
}

function make_directory_TEST()
{
    [[ -d "$1" ]]
}

function make_directory_SHELL()
{
    mkdir -p "$1"
}

# --------------------------------------------------------------------------------
function copy_file_DESC()
{
    echo "copy \"$1\" to \"$2\""
}

function copy_file_TEST()
{
    [[ -f "$2" ]]
}

function copy_file_SHELL()
{
    cp -a "$1" "$2"
}
