#!/bin/bash
#
# Box download and load
#

BOX_CONFIG_FILE=$PISH_BOX/$BOX_CONFIG/pish-config
BOX_CONFIG_PULLED=false
BOX_CONFIG_LOADED=false

# ================================================================================
# Box download
#
function box_download_DESC()
{
    echo "box '$BOX_CONFIG' is downloaded"
}

function box_download_TEST()
{
    test -d $PISH_BOX/$BOX_CONFIG
}

function box_download_SHELL()
{
    git clone $PISH_BOX_URL/$BOX_CONFIG $PISH_BOX/$BOX_CONFIG
}

# ================================================================================
# Box pull
#
function box_pull_PREQ()
{
    requirement ssh_has_keys
    requirement box_download
}

function box_pull_DESC()
{
    echo "box '$BOX_CONFIG' is up to date"
}

function box_pull_TEST()
{
    local status=$BOX_CONFIG_PULLED
    BOX_CONFIG_PULLED=true
    $status
}

function box_pull_SHELL()
{
    cd $PISH_BOX/$BOX_CONFIG
    git pull
}

# ================================================================================
# Box loader
#
function box_load_PREQ()
{
    requirement box_pull
}

function box_load_DESC()
{
    echo "box '$BOX_CONFIG' is loaded"
}

function box_load_TEST()
{
    $BOX_CONFIG_LOADED
}

function box_load_LOCAL()
{
    if [[ ! -f $BOX_CONFIG_FILE ]]; then
	error "'$BOX_CONFIG' must have '$BOX_CONFIG_FILE'"
    fi

    # Load it
    . $BOX_CONFIG_FILE
    BOX_CONFIG_LOADED=true
}
