#!/bin/bash
#
# Box download and load
#

BOX_CONFIG_FILE=$PISH_BOX/$BOX_CONFIG/pish-config
BOX_CONFIG_PULLED=false
BOX_CONFIG_LOADED=false

BOX_USER_CONFIG_URL=git@github.com:harveyt/config.git

# ================================================================================
# Box download
#
function box_download_DESC()
{
    echo "box '$BOX_CONFIG' is downloaded"
}

function box_download_TEST()
{
    test -d $PISH_BOX/$BOX_CONFIG
}

function box_download_SHELL()
{
    git clone $PISH_BOX_URL/$BOX_CONFIG $PISH_BOX/$BOX_CONFIG
}

# ================================================================================
# Box pull
#
function box_pull_PREQ()
{
    requirement ssh_has_keys
    requirement box_download
}

function box_pull_DESC()
{
    echo "box '$BOX_CONFIG' is up to date"
}

function box_pull_TEST()
{
    local status=$BOX_CONFIG_PULLED
    BOX_CONFIG_PULLED=true
    $status
}

function box_pull_SHELL()
{
    cd $PISH_BOX/$BOX_CONFIG
    git pull
}

# ================================================================================
# Box loader
#
function box_load_PREQ()
{
    requirement box_pull
}

function box_load_DESC()
{
    echo "box '$BOX_CONFIG' is loaded"
}

function box_load_TEST()
{
    $BOX_CONFIG_LOADED
}

function box_load_LOCAL()
{
    if [[ ! -f $BOX_CONFIG_FILE ]]; then
	error "'$BOX_CONFIG' must have '$BOX_CONFIG_FILE'"
    fi

    # Load it
    . $BOX_CONFIG_FILE
    BOX_CONFIG_LOADED=true
}

# ================================================================================
# Box user config

function box_user_config_PREQ()
{
    requirement ssh_has_keys
}

function box_user_config_DESC()
{
    echo "box user config is present"
}

function box_user_config_TEST()
{
    test -d $HOME/bin
}

function box_user_config_install_config()
{
    if [[ ! -d $HOME/config ]]; then
	return
    fi
    for src in $HOME/config/.[^.]* $HOME/config/*
    do
	dst="$HOME/$(basename "$src")"

	if [[ -e "$dst" ]]; then
	    dst_orig="$dst-ORIG"
	    echo "WARNING: $dst saved as $dst_orig"
	    mv "$dst" "$dst-ORIG"
	fi
	mv "$src" "$dst"
    done
    rmdir $HOME/config
}

function box_user_config_install_ssh()
{
    if [[ ! -d $HOME/.ssh ]]; then
	return
    fi
    for src in $HOME/.ssh/*
    do
	dst="$HOME/lib/ssh/$(basename "$src")"
	if [[ -e "$dst" ]]; then
	    dst_orig="$dst-ORIG"
	    echo "WARNING: $dst saved as $dst_orig"
	    mv "$dst" "$dst-ORIG"
	fi
	mv "$src" "$dst"
    done
    rmdir $HOME/.ssh
    ln -s $HOME/lib/ssh $HOME/.ssh
}

function box_user_config_SHELL()
{
    cd $HOME
    mkdir -p $HOME/config
    git clone $BOX_USER_CONFIG_URL $HOME/config

    box_user_config_install_config
    box_user_config_install_ssh
}
