#!/bin/bash
#
# Git utilities
#

PROJECTS_ROOT="$HOME/Projects"

# ================================================================================
# Git clone

function git_clone_DESC()
{
    local url="$1"
    local dir="$2"
    echo "clone repository '$url' to '$dir'"
}

function git_clone_TEST()
{
    local dir="$2"
    test -d "$dir"    
}

function git_clone_SHELL()
{
    local url="$1"
    local dir="$2"
    git clone --origin=$USER "$url" "$dir"
}

# ================================================================================
# Project git clone

function git_clone_project_DESC()
{
    local url="$1"
    echo "clone repository '$url' to projects"
}

function git_clone_project_TEST()
{
    local url="$1"
    local dir="$(basename "$url")"
    local path="$PROJECTS_ROOT/$dir"

    test -d "$path"
}

function git_clone_project_SHELL()
{
    local url="$1"
    local dir="$(basename "$url")"
    local path="$PROJECTS_ROOT/$dir"

    git clone --origin=$USER "$url" "$path"
}
