#!/bin/bash
#
# Provision In SHell.
#
# Version: %%VERSION%%
#
# %%LICENSE%%
#

# ================================================================================
# Requirements for homebrew
#
function homebrew_install_PREQ()
{
    requirement sudo_cache_root_password
}

function homebrew_install_DESC()
{
    echo "install homebrew"
}

function homebrew_install_TEST()
{
   type -p brew >/dev/null
}

function homebrew_install_SHELL()
{
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" </dev/null
}

# --------------------------------------------------------------------------------

function brew_install_PREQ()
{
    requirement homebrew_install
}

function brew_install_DESC()
{
    local name="$1"
    shift
    echo "brew install $name $@"
}

function brew_install_TEST()
{
    local name="$1"    
    brew ls --versions "$name" >/dev/null
}

function brew_install_SHELL()
{
    local name="$1"
    shift
    brew install "$name" "$@"
}

# --------------------------------------------------------------------------------

function brew_install_version_PREQ()
{
    local name="$1"
    local version="$2"
    requirement homebrew_install
    requirement brew_install "$name@$version"
}

function brew_install_version_DESC()
{
    local name="$1"
    local version="$2"
    echo "brew installed $name linked as version $version"
}

function brew_install_version_TEST()
{
    local name="$1"
    local version="$2"
    local linked="$(brew info --json=v1 "$name@$version" | jq -r '.[0].linked_keg')"

    [[ "$linked" == $version* ]]
}

function brew_install_version_SHELL()
{
    local name="$1"
    local version="$2"

    brew link --force "$name@$version"
}

# --------------------------------------------------------------------------------

function brew_cask_install_PREQ()
{
    requirement homebrew_install
}

function brew_cask_install_DESC()
{
    local name="$1"
    echo "brew cask install $name"
}

function brew_cask_install_TEST()
{
    local name="$1"    
    brew cask list "$name" >/dev/null 2>&1
}

function brew_cask_install_SHELL()
{
    local name="$1"
    brew cask install "$name"
}

# --------------------------------------------------------------------------------

function brew_service_running_PREQ()
{
    requirement homebrew_install
}

function brew_service_running_DESC()
{
    local name="$1"
    echo "brew services $name is running"
}

function brew_service_running_TEST()
{
    local name="$1"
    local status="$(brew services list | awk '$1 == "'"$name"'" { print $2 }')"
    
    [[ "$status" == "started" ]]
}

function brew_service_running_SHELL()
{
    local name="$1"
    
    brew services start "$name"
}

# --------------------------------------------------------------------------------

function brew_tap_PREQ()
{
    requirement homebrew_install
}

function brew_tap_DESC()
{
    local name="$1" tap="$2"
    echo "brew tap $name"
}

function brew_tap_TEST()
{
    local name="$1" tap="$2"
    brew tap 2>/dev/null | grep -q -x "$tap" 2>/dev/null
}

function brew_tap_SHELL()
{
    local name="$1"
    brew tap "$name"
}

# --------------------------------------------------------------------------------

function brew_linkapp_PREQ()
{
    requirement sudo_cache_root_password
}

function brew_linkapp_DESC()
{
    local path="$1"
    local name="$2"
    echo "brew linkapp $path as $name"
}

function brew_linkapp_TEST()
{
    local path="$1"
    local name="$2"
    [[ -d /Applications/$name.app ]]
}

function brew_linkapp_SHELL()
{
    local path="$1"
    local name="$2"
    sudo ln -s $path /Applications/$name.app
}
