#!/bin/bash
#
# Provision In SHell.
#
# Version: %%VERSION%%
#
# %%LICENSE%%
#

# ================================================================================
# Requirements for homebrew
#
function homebrew_install_PREQ()
{
    requirement sudo_cache_root_password
}

function homebrew_install_DESC()
{
    echo "install homebrew"
}

function homebrew_install_TEST()
{
   type -p brew >/dev/null
}

function homebrew_install_SHELL()
{
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" </dev/null
}

# --------------------------------------------------------------------------------

function brew_install_PREQ()
{
    requirement homebrew_install
}

function brew_install_DESC()
{
    local name="$1"
    echo "brew install $name"
}

function brew_install_TEST()
{
    local name="$1"    
    brew ls --versions "$name" >/dev/null
}

function brew_install_SHELL()
{
    local name="$1"
    brew install "$name"
}

# --------------------------------------------------------------------------------

function brew_cask_install_PREQ()
{
    requirement homebrew_install
}

function brew_cask_install_DESC()
{
    local name="$1"
    echo "brew cask install $name"
}

function brew_cask_install_TEST()
{
    local name="$1"    
    brew cask list "$name" >/dev/null 2>&1
}

function brew_cask_install_SHELL()
{
    local name="$1"
    brew cask install "$name"
}
