#!/bin/bash
#
# GitHub / BitBucket / SSH Access
#

# ================================================================================
# Get SSH configuration

function ssh_has_keys_PREQ()
{
    requirement 1pass_logged_in
}

function ssh_has_keys_DESC()
{
    echo "has SSH keys from 1Password"
}
    
function ssh_has_keys_TEST()
{
    test -f $SSH_ID_RSA -a $SSH_ID_RSA_PUB
}

function ssh_has_keys_LOCAL()
{
    if [[ ! -d $SSH_DIR ]]; then
	mkdir -p $SSH_DIR
    fi
    if [[ ! -f $SSH_ID_RSA ]]; then
	$OP document get "$PISH_BOX - id_rsa" --output=$SSH_ID_RSA
    fi
    if [[ ! -f $SSH_ID_RSA_PUB ]]; then
	$OP document get "$PISH_BOX - id_rsa.pub" --output=$SSH_ID_RSA_PUB
    fi
}

# ================================================================================
# Ensure SSH known hosts is present

function ssh_known_hosts_DESC()
{
    local host="$1"
    echo "ensure known host for '$host'"
}
    
function ssh_known_hosts_TEST()
{
    local host="$1"
    local entry="$(ssh-keygen -H -F "$host" 2>/dev/null)"
    [[ "$entry" != "" ]]
}

function ssh_known_hosts_LOCAL()
{
    local host="$1"
    ssh-keyscan -H "$host" >> $SSH_DIR/known_hosts
}
